### PR TITLE
Initialize a go module

### PR DESCRIPTION
**Pull request by joezak11**

### CODE REVIEW

**Comment by nwg-piotr** [comment]
Wow, I was just about to archive this repo. Should I keep it alive?

**Comment by joezak11** [comment]
I'm not sure of my ability to contribute to any serious code to be honest XD, but a go implementation would be more interesting than python in my opinion.

**Comment by nwg-piotr** [comment]
You mean the panel, I suppose? I chose python due to the code maintainability and OOP. The latter goes well with many instances of the same thing. Also gotk3 misses some important GTK bindings.

**Comment by joezak11** [comment]
I see. Would Rust be considered as  a potential candidate, though?

**Comment by nwg-piotr** [comment]
Honestly: I tried learning rust, but I'm a 55 y.o. hobbyist, not a pro. It seems too difficult to me.

**Comment by joezak11** [comment]
I see. I guess python is the easiest way to get the job done. I'm no expert in the matter XD. Golang can be frustrating sometimes with error handling and their "OOP" implementation.

**Comment by nwg-piotr** [comment]
I like their error handling. But some things need to wait for better gtk bindings. I tried gotk4 tonight, but couldn't build the simplest example for some reason.

**Pull request merged**
